/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as MeRouteImport } from './routes/me'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HadithsRouteImport } from './routes/hadiths'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as QuizzesIdRouteImport } from './routes/quizzes.$id'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'
import { Route as HadithsNawawiRouteImport } from './routes/hadiths.nawawi'
import { Route as HadithsMuslimRouteImport } from './routes/hadiths.muslim'
import { Route as HadithsBukhariRouteImport } from './routes/hadiths.bukhari'
import { Route as HadithsNumberRouteImport } from './routes/hadiths.$number'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as HadithsCollectionNumberRouteImport } from './routes/hadiths.$collection.$number'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithsRoute = HadithsRouteImport.update({
  id: '/hadiths',
  path: '/hadiths',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const QuizzesIdRoute = QuizzesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuizzesRoute,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LessonsRoute,
} as any)
const HadithsNawawiRoute = HadithsNawawiRouteImport.update({
  id: '/nawawi',
  path: '/nawawi',
  getParentRoute: () => HadithsRoute,
} as any)
const HadithsMuslimRoute = HadithsMuslimRouteImport.update({
  id: '/muslim',
  path: '/muslim',
  getParentRoute: () => HadithsRoute,
} as any)
const HadithsBukhariRoute = HadithsBukhariRouteImport.update({
  id: '/bukhari',
  path: '/bukhari',
  getParentRoute: () => HadithsRoute,
} as any)
const HadithsNumberRoute = HadithsNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => HadithsRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const HadithsCollectionNumberRoute = HadithsCollectionNumberRouteImport.update({
  id: '/$collection/$number',
  path: '/$collection/$number',
  getParentRoute: () => HadithsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/hadiths': typeof HadithsRouteWithChildren
  '/journey': typeof JourneyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/me': typeof MeRoute
  '/password-reset': typeof PasswordResetRoute
  '/questions': typeof QuestionsRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/quran': typeof QuranRoute
  '/search': typeof SearchRoute
  '/stories': typeof StoriesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/hadiths/$number': typeof HadithsNumberRoute
  '/hadiths/bukhari': typeof HadithsBukhariRoute
  '/hadiths/muslim': typeof HadithsMuslimRoute
  '/hadiths/nawawi': typeof HadithsNawawiRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/hadiths/$collection/$number': typeof HadithsCollectionNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/hadiths': typeof HadithsRouteWithChildren
  '/journey': typeof JourneyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/me': typeof MeRoute
  '/password-reset': typeof PasswordResetRoute
  '/questions': typeof QuestionsRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/quran': typeof QuranRoute
  '/search': typeof SearchRoute
  '/stories': typeof StoriesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/hadiths/$number': typeof HadithsNumberRoute
  '/hadiths/bukhari': typeof HadithsBukhariRoute
  '/hadiths/muslim': typeof HadithsMuslimRoute
  '/hadiths/nawawi': typeof HadithsNawawiRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/hadiths/$collection/$number': typeof HadithsCollectionNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/hadiths': typeof HadithsRouteWithChildren
  '/journey': typeof JourneyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/me': typeof MeRoute
  '/password-reset': typeof PasswordResetRoute
  '/questions': typeof QuestionsRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/quran': typeof QuranRoute
  '/search': typeof SearchRoute
  '/stories': typeof StoriesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/hadiths/$number': typeof HadithsNumberRoute
  '/hadiths/bukhari': typeof HadithsBukhariRoute
  '/hadiths/muslim': typeof HadithsMuslimRoute
  '/hadiths/nawawi': typeof HadithsNawawiRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/hadiths/$collection/$number': typeof HadithsCollectionNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/dashboard'
    | '/favorites'
    | '/hadiths'
    | '/journey'
    | '/leaderboard'
    | '/lessons'
    | '/me'
    | '/password-reset'
    | '/questions'
    | '/quizzes'
    | '/quran'
    | '/search'
    | '/stories'
    | '/verify-email'
    | '/articles/$slug'
    | '/hadiths/$number'
    | '/hadiths/bukhari'
    | '/hadiths/muslim'
    | '/hadiths/nawawi'
    | '/lessons/$slug'
    | '/quizzes/$id'
    | '/stories/$slug'
    | '/hadiths/$collection/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/dashboard'
    | '/favorites'
    | '/hadiths'
    | '/journey'
    | '/leaderboard'
    | '/lessons'
    | '/me'
    | '/password-reset'
    | '/questions'
    | '/quizzes'
    | '/quran'
    | '/search'
    | '/stories'
    | '/verify-email'
    | '/articles/$slug'
    | '/hadiths/$number'
    | '/hadiths/bukhari'
    | '/hadiths/muslim'
    | '/hadiths/nawawi'
    | '/lessons/$slug'
    | '/quizzes/$id'
    | '/stories/$slug'
    | '/hadiths/$collection/$number'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/dashboard'
    | '/favorites'
    | '/hadiths'
    | '/journey'
    | '/leaderboard'
    | '/lessons'
    | '/me'
    | '/password-reset'
    | '/questions'
    | '/quizzes'
    | '/quran'
    | '/search'
    | '/stories'
    | '/verify-email'
    | '/articles/$slug'
    | '/hadiths/$number'
    | '/hadiths/bukhari'
    | '/hadiths/muslim'
    | '/hadiths/nawawi'
    | '/lessons/$slug'
    | '/quizzes/$id'
    | '/stories/$slug'
    | '/hadiths/$collection/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  HadithsRoute: typeof HadithsRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  MeRoute: typeof MeRoute
  PasswordResetRoute: typeof PasswordResetRoute
  QuestionsRoute: typeof QuestionsRoute
  QuizzesRoute: typeof QuizzesRouteWithChildren
  QuranRoute: typeof QuranRoute
  SearchRoute: typeof SearchRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadiths': {
      id: '/hadiths'
      path: '/hadiths'
      fullPath: '/hadiths'
      preLoaderRoute: typeof HadithsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/quizzes/$id': {
      id: '/quizzes/$id'
      path: '/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof QuizzesIdRouteImport
      parentRoute: typeof QuizzesRoute
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/hadiths/nawawi': {
      id: '/hadiths/nawawi'
      path: '/nawawi'
      fullPath: '/hadiths/nawawi'
      preLoaderRoute: typeof HadithsNawawiRouteImport
      parentRoute: typeof HadithsRoute
    }
    '/hadiths/muslim': {
      id: '/hadiths/muslim'
      path: '/muslim'
      fullPath: '/hadiths/muslim'
      preLoaderRoute: typeof HadithsMuslimRouteImport
      parentRoute: typeof HadithsRoute
    }
    '/hadiths/bukhari': {
      id: '/hadiths/bukhari'
      path: '/bukhari'
      fullPath: '/hadiths/bukhari'
      preLoaderRoute: typeof HadithsBukhariRouteImport
      parentRoute: typeof HadithsRoute
    }
    '/hadiths/$number': {
      id: '/hadiths/$number'
      path: '/$number'
      fullPath: '/hadiths/$number'
      preLoaderRoute: typeof HadithsNumberRouteImport
      parentRoute: typeof HadithsRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/hadiths/$collection/$number': {
      id: '/hadiths/$collection/$number'
      path: '/$collection/$number'
      fullPath: '/hadiths/$collection/$number'
      preLoaderRoute: typeof HadithsCollectionNumberRouteImport
      parentRoute: typeof HadithsRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface HadithsRouteChildren {
  HadithsNumberRoute: typeof HadithsNumberRoute
  HadithsBukhariRoute: typeof HadithsBukhariRoute
  HadithsMuslimRoute: typeof HadithsMuslimRoute
  HadithsNawawiRoute: typeof HadithsNawawiRoute
  HadithsCollectionNumberRoute: typeof HadithsCollectionNumberRoute
}

const HadithsRouteChildren: HadithsRouteChildren = {
  HadithsNumberRoute: HadithsNumberRoute,
  HadithsBukhariRoute: HadithsBukhariRoute,
  HadithsMuslimRoute: HadithsMuslimRoute,
  HadithsNawawiRoute: HadithsNawawiRoute,
  HadithsCollectionNumberRoute: HadithsCollectionNumberRoute,
}

const HadithsRouteWithChildren =
  HadithsRoute._addFileChildren(HadithsRouteChildren)

interface LessonsRouteChildren {
  LessonsSlugRoute: typeof LessonsSlugRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsSlugRoute: LessonsSlugRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

interface QuizzesRouteChildren {
  QuizzesIdRoute: typeof QuizzesIdRoute
}

const QuizzesRouteChildren: QuizzesRouteChildren = {
  QuizzesIdRoute: QuizzesIdRoute,
}

const QuizzesRouteWithChildren =
  QuizzesRoute._addFileChildren(QuizzesRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  HadithsRoute: HadithsRouteWithChildren,
  JourneyRoute: JourneyRoute,
  LeaderboardRoute: LeaderboardRoute,
  LessonsRoute: LessonsRouteWithChildren,
  MeRoute: MeRoute,
  PasswordResetRoute: PasswordResetRoute,
  QuestionsRoute: QuestionsRoute,
  QuizzesRoute: QuizzesRouteWithChildren,
  QuranRoute: QuranRoute,
  SearchRoute: SearchRoute,
  StoriesRoute: StoriesRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
